---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  # default opscode-centos-5.10 box prior to chef installation
  - name: centos-5.10-opscode
    driver:
      box: opscode-centos-5.10

  # default opscode-centos-6.5 box prior to chef installation
  - name: centos-6.5-opscode
    driver:
      box: opscode-centos-6.5

  # locally-provisioned opscode-centos-5.10 box with omnibus chef 11.8.2
  - name: centos-5.10-chef-11.8.2
    driver:
      box: opscode-centos-5.10-chef-11.8.2

  # locally-provisioned opscode-centos-6.5 box with omnibus chef 11.8.2
  - name: centos-6.5-chef-11.8.2
    driver:
      box: opscode-centos-6.5-chef-11.8.2

suites:
  - name: bootstrap
    run_list:
      - 'recipe[bootstrap::rhel]'
    attributes:
      authorization:
        sudo:
          users:
            - vagrant
          passwordless: true
