---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: rhel
    run_list:
      - recipe[bootstrap::rhel]
    attributes:
      authorization:
        sudo:
          users:
            - vagrant
          passwordless: true
